service: posts

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  resourceStageBuilder: ${file(env.yml):${self:provider.stage}.resourceStageBuilder}
  domainName: ${file(env.yml):${self:provider.stage}.domainName}
  memorySize: 512
  timeout: 10

  iamRoleStatements:
  - Effect: Allow
    Action:
    - KMS:Decrypt
    Resource: ${file(env.yml):${self:provider.stage}.kmsKeyArn}
  - Effect: Allow
    Action:
    - S3:ListBucket
    Resource: arn:aws:s3:::randytarampi-${self:provider.stage}-posts
  - Effect: Allow
    Action:
    - S3:GetObject
    Resource: arn:aws:s3:::randytarampi-${self:provider.stage}-posts/*
  - Effect: Allow
    Action:
    - SNS:Publish
    Resource:
      Ref: LambdaDeadLetterQueue
  - Effect: Allow
    Action:
    - dynamodb:*
    Resource: arn:aws:dynamodb:${self:provider.region}:471964952458:table/${self:provider.environment.POSTS_DYNAMODB_TABLE}

  environment: ${file(env.yml):${self:provider.stage}.environment}
  environmentSecrets: # can't just include the whole obj from the env file bc for some reason the plugin won't load from external files
    FLICKR_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.FLICKR_API_KEY}
    FLICKR_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.FLICKR_API_SECRET}
    UNSPLASH_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.UNSPLASH_API_KEY}
    UNSPLASH_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.UNSPLASH_API_SECRET}
    INSTAGRAM_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.INSTAGRAM_API_KEY}
    INSTAGRAM_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.INSTAGRAM_API_SECRET}
    INSTAGRAM_ACCESS_TOKEN: ${file(env.yml):${self:provider.stage}.environmentSecrets.INSTAGRAM_ACCESS_TOKEN}
    TUMBLR_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.TUMBLR_API_KEY}
    TUMBLR_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.TUMBLR_API_SECRET}
    SENTRY_DSN: ${file(env.yml):${self:provider.stage}.environmentSecrets.SENTRY_DSN}

package:
  individually: true

plugins:
- serverless-secrets
- serverless-webpack
- serverless-dynamodb-local
- serverless-offline
- serverless-mocha-plugin
- serverless-domain-manager

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
    #      sharedDb: true
    migration:
      dir: serverless/dynamoDb/migrations
  webpack:
    webpackConfig: ./webpack.serverless.config.js
    includeModules:
      forceInclude:
      - mime
      forceExclude:
      - aws-sdk
  serverlessSecrets:
    throwOnMissingSecret: true
    providerOptions:
      region: ${self:provider.region}
    keys:
      dev: "alias/serverless-dev"
      prd: "alias/serverless-prd"
  alarmTopic: ${file(env.yml):${self:provider.stage}.alarmTopic}
  serverless-offline:
    port: 3006
  customDomain:
    domainName: ${file(env.yml):${self:provider.stage}.domainName}
    certificateName: ${file(env.yml):${self:provider.stage}.acmName}
    createRoute53Record: true
    basePath: ""

functions:
  getPosts:
    handler: serverless/handler/initializedGetPosts.default
    events:
    - http:
        path: ${self:service}
        method: get
        cors: true
    onError:
      Ref: LambdaDeadLetterQueue
  getWords:
    handler: serverless/handler/initializedGetWords.default
    events:
    - http:
        path: words
        method: get
        cors: true
    onError:
      Ref: LambdaDeadLetterQueue
  getPhotos:
    handler: serverless/handler/initializedGetPhotos.default
    events:
    - http:
        path: photos
        method: get
        cors: true
    onError:
      Ref: LambdaDeadLetterQueue
  instagramAuthRedirect:
    handler: serverless/handler/initializedInstagramAuthRedirect.default
    events:
    - http:
        path: auth/instagram
        method: get
        cors: true
    onError:
      Ref: LambdaDeadLetterQueue
  instagramAuthReturn:
    handler: serverless/handler/initializedInstagramAuthReturn.default
    events:
    - http:
        path: auth/instagram/redirect
        method: get
        cors: true
    onError:
      Ref: LambdaDeadLetterQueue

resources:
  Resources:
    LambdaDeadLetterQueue:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:provider.resourceStageBuilder}-${self:service}-lambda-dlq
        TopicName: ${self:provider.resourceStageBuilder}-${self:service}-lambda-dlq
    ErrorsAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: Lambda errors
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        Namespace: AWS/Lambda
        MetricName: Errors
        Period: 60
        Statistic: Sum
        Threshold: 1
        Unit: Count
    DurationAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: Long running lambdas
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        Namespace: AWS/Lambda
        MetricName: Duration
        Threshold: 5000
        Period: 60
        Statistic: Maximum
        Unit: Milliseconds
    Gateway4xxAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: 4xx Errors
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
        - Value: ${self:provider.stage}-${self:service}
          Name: ApiName
        - Value: ${self:provider.stage}
          Name: Stage
        EvaluationPeriods: 1
        Namespace: AWS/ApiGateway
        MetricName: 4XXError
        Period: 60
        Statistic: Average
        Threshold: 0.1
        Unit: Count
    Gateway5xxAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: 5xx Errors
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
        - Value: ${self:provider.stage}-${self:service}
          Name: ApiName
        - Value: ${self:provider.stage}
          Name: Stage
        EvaluationPeriods: 1
        Namespace: AWS/ApiGateway
        MetricName: 5XXError
        Period: 60
        Statistic: Average
        Threshold: 0.1
        Unit: Count
    S3BucketPosts:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET_NAME}
