service: posts

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  resourceStageBuilder: ${file(env.yml):${self:provider.stage}.resourceStageBuilder}
  baseDomainName: ${file(env.yml):${self:provider.stage}.baseDomainName}
  domainName: ${file(env.yml):${self:provider.stage}.domainName}
  memorySize: 256
  timeout: 10

  apiKeys:
  - ${self:provider.stage}-${self:service}-user

  iamRoleStatements:
  - Effect: Allow
    Action:
    - KMS:Decrypt
    Resource: ${file(env.yml):${self:provider.stage}.kmsKeyArn}
  - Effect: Allow
    Action:
    - S3:ListBucket
    Resource: arn:aws:s3:::randytarampi-${self:provider.stage}-${self:service}
  - Effect: Allow
    Action:
    - S3:GetObject
    Resource: arn:aws:s3:::randytarampi-${self:provider.stage}-${self:service}/*
  - Effect: Allow
    Action:
    - SNS:Publish
    Resource:
      Ref: LambdaDeadLetterQueue
  - Effect: Allow
    Action:
    - dynamodb:*
    Resource: arn:aws:dynamodb:${self:provider.region}:471964952458:table/${self:provider.environment.POSTS_DYNAMODB_TABLE}
  - Effect: Allow
    Action:
    - dynamodb:*
    Resource: arn:aws:dynamodb:${self:provider.region}:471964952458:table/${self:provider.environment.POSTS_DYNAMODB_TABLE}/*
  - Effect: Allow
    Action:
    - lambda:InvokeFunction
    Resource: arn:aws:lambda:${self:provider.region}:471964952458:function:${self:service}-${self:provider.stage}-*

  environment: ${file(env.yml):${self:provider.stage}.environment}
  environmentSecrets: # NOTE-RT: Can't just go `${file(env.yml):${self:provider.stage}.environmentSecrets}` because `serverless-secrets` makes assumptions about what's actually in your configuration file
    FLICKR_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.FLICKR_API_KEY}
    FLICKR_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.FLICKR_API_SECRET}
    UNSPLASH_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.UNSPLASH_API_KEY}
    UNSPLASH_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.UNSPLASH_API_SECRET}
    INSTAGRAM_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.INSTAGRAM_API_KEY}
    INSTAGRAM_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.INSTAGRAM_API_SECRET}
    INSTAGRAM_ACCESS_TOKEN: ${file(env.yml):${self:provider.stage}.environmentSecrets.INSTAGRAM_ACCESS_TOKEN}
    TUMBLR_API_KEY: ${file(env.yml):${self:provider.stage}.environmentSecrets.TUMBLR_API_KEY}
    TUMBLR_API_SECRET: ${file(env.yml):${self:provider.stage}.environmentSecrets.TUMBLR_API_SECRET}
    SENTRY_DSN: ${file(env.yml):${self:provider.stage}.environmentSecrets.SENTRY_DSN}

package:
  individually: true

plugins:
- serverless-secrets
- serverless-webpack
- serverless-dynamodb-local
- serverless-plugin-warmup
- serverless-offline
- serverless-mocha-plugin
- serverless-domain-manager

custom:
  dynamodb:
    start:
      port: ${file(./serverless/util/loadConfig.js):default.posts.dbPort}
      inMemory: true
      # sharedDb: true
    migration:
      dir: serverless/dynamoDb/migrations
  webpack:
    webpackConfig: ./webpack.serverless.config.js
    includeModules:
      forceInclude:
      - mime
      forceExclude:
      - aws-sdk
  serverlessSecrets:
    throwOnMissingSecret: true
    providerOptions:
      region: ${self:provider.region}
    keys:
      dev: "alias/serverless-dev"
      prd: "alias/serverless-prd"
  alarmTopic: ${file(env.yml):${self:provider.stage}.alarmTopic}
  serverless-offline:
    port: ${file(./serverless/util/loadConfig.js):default.posts.serverPort}
  customDomain:
    domainName: ${file(env.yml):${self:provider.stage}.domainName}
    certificateName: ${file(env.yml):${self:provider.stage}.acmName}
    createRoute53Record: true
    basePath: ""
  warmup:
    prewarm: true

functions: # NOTE-RT: Can't just go `${file(env.yml):${self:provider.stage}.functions}` because `serverless-secrets` makes assumptions about what's actually in your configuration file
  cachePosts:
    handler: serverless/handlers/cachePosts/initialized.default
    timeout: 60
    events: ${file(env.yml):${self:provider.stage}.functions.cachePosts.events}
    onError:
      Ref: LambdaDeadLetterQueue
  getPosts:
    warmup: true
    handler: serverless/handlers/getPosts/initialized.default
    events: ${file(env.yml):${self:provider.stage}.functions.getPosts.events}
    onError:
      Ref: LambdaDeadLetterQueue
  instagramAuthRedirect:
    handler: serverless/handlers/instagramAuthRedirect/initialized.default
    events: ${file(env.yml):${self:provider.stage}.functions.instagramAuthRedirect.events}
    onError:
      Ref: LambdaDeadLetterQueue
  instagramAuthReturn:
    handler: serverless/handlers/instagramAuthReturn/initialized.default
    events: ${file(env.yml):${self:provider.stage}.functions.instagramAuthReturn.events}
    onError:
      Ref: LambdaDeadLetterQueue

resources:
  Resources:
    LambdaDeadLetterQueue:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:provider.resourceStageBuilder}-${self:service}-lambda-dlq
        TopicName: ${self:provider.resourceStageBuilder}-${self:service}-lambda-dlq
    ErrorsAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: Lambda errors
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        Namespace: AWS/Lambda
        MetricName: Errors
        Period: 60
        Statistic: Sum
        Threshold: 1
        Unit: Count
    DurationAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: Long running lambdas
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        Namespace: AWS/Lambda
        MetricName: Duration
        Threshold: 15000
        Period: 60
        Statistic: Maximum
        Unit: Milliseconds
    Gateway4xxAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: 4xx Errors
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
        - Value: ${self:provider.stage}-${self:service}
          Name: ApiName
        - Value: ${self:provider.stage}
          Name: Stage
        EvaluationPeriods: 1
        Namespace: AWS/ApiGateway
        MetricName: 4XXError
        Period: 60
        Statistic: Average
        Threshold: 0.1
        Unit: Count
    Gateway5xxAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
        - ${self:custom.alarmTopic}
        AlarmDescription: 5xx Errors
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
        - Value: ${self:provider.stage}-${self:service}
          Name: ApiName
        - Value: ${self:provider.stage}
          Name: Stage
        EvaluationPeriods: 1
        Namespace: AWS/ApiGateway
        MetricName: 5XXError
        Period: 60
        Statistic: Average
        Threshold: 0.1
        Unit: Count
    S3BucketPosts:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET_NAME}
