twitter:
  app:
    id: 12953440
github:
  app:
    id: a9cfba4f2c99ad5f8e8d
instagram:
  app:
    id: c80068a8272c4953908ae92a7113d473
gtm:
  container:
    id: GTM-W6NFL6M
ga:
  property:
    id: UA-50921068-6
mixpanel:
  app:
    id: 0c0d4669fdc9a52ecb789ab3c27cc900
crisp:
  app:
    id: 03689d2b-80ab-4f5d-90cb-a2de269ea9c3
sentry:
  dsn: https://5f246bd3456d477da7ebf2d4fd06f2bb@sentry.io/1240735
gcp:
  api:
    key: AIzaSyDp9DoelWlkF7KYaUgw7HElwmMQFQMVu_Q
posts:
  photosUrl: https://service.dev.randytarampi.ca/posts?type=Photo
  postsUrl: https://service.dev.randytarampi.ca/posts
  wordsUrl: https://service.dev.randytarampi.ca/posts?type=Post
  feedUrl: https://service.dev.randytarampi.ca/posts/feed.rss
  resumeUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/resume/src/resumes
  letterUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/letter/src/letters
www:
  publishUrl: https://dev.randytarampi.ca
  assetUrl: &wwwAssetUrl ""
resume:
  publishUrl: https://dev.randytarampi.ca/resume
  assetUrl: *wwwAssetUrl
letter:
  publishUrl: https://dev.randytarampi.ca/letter
  assetUrl: *wwwAssetUrl
logger:
  streams:
    stdout: true
    sentry: true
    human: false
    console: true
  level: debug
  src: true
