twitter:
  app:
    id: 12953435
github:
  app:
    id: 0fce69fae690aaaa7e49
facebook:
  app:
    id: 1705404522846104
instagram:
  app:
    id: 5c8f5711cf364247b174e30612c5e0dd
gtm:
  container:
    id: GTM-W6NFL6M
ga:
  property:
    id: UA-50921068-1
mixpanel:
  app:
    id: 388362ac34ccae4a08c1dbf86791e4ee
crisp:
  app:
    id: 7b5aa3db-d25f-4abf-9d9d-85f62d9c1428
sentry:
  dsn: https://5f246bd3456d477da7ebf2d4fd06f2bb@sentry.io/1240735
gcp:
  api:
    key: AIzaSyCkMBpsbrY5zpOUAwyHsBGoHawaTPwg3yM
posts:
  photosUrl: https://service.randytarampi.ca/posts?type=Photo
  postsUrl: https://service.randytarampi.ca/posts
  wordsUrl: https://service.randytarampi.ca/posts?type=Post
  feedUrl: https://service.randytarampi.ca/posts/feed.rss
  resumeUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/resume/src/resumes
  letterUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/letter/src/letters
www:
  publishUrl: https://www.randytarampi.ca
  assetUrl: &wwwAssetUrl ""
resume:
  publishUrl: https://www.randytarampi.ca/resume
  assetUrl: *wwwAssetUrl
letter:
  publishUrl: https://www.randytarampi.ca/letter
  assetUrl: *wwwAssetUrl
logger:
  streams:
    stdout: true
    sentry: true
    human: false
    console: true
  level: info
  src: false
