language: node_js
dist: trusty
node_js:
- '8'
env:
  global:
  - secure: xPu80KstQbKNLUII+023NQmFzHvjD4fSLKk4B4yDaOGRNmZ7gScbpWYLgYZUw7klwo571IdbNA1FGVo0J6k4yV3LfT4oCTPAR9AL62OcZZIiTWUvHtenZEYFVpppDeORmayq3/0ISSLBEYJCxt0qqtNIcs0nWmlUTBvWL4uncrxEUcPUSUf1BTIECwHw1jpqe6R3RHI550xCor8ZH0opam1xkyDA86duAJtSxEs8sKj1D2vhvLxQvKfgnQKmr2xf46DY1+TdbxafVDLqaoSc4QRyNBOlavO0+hnpqQftIWO+SG1C36DJ0oTvr2QdZLlH5OZP7DYmOr076xK8i+dY1aXm6Qi9XQL58xlMwLORiGoDE+zp6iSDjafw4+pBe4AMZv/7Ddxt+19WoVWJzDZqPxyjZFlqGv/V4lpnuOGS9AkAzOy1qeDlClOqll823Md2vaKn5MX/CE8wOzAH/C/3Uf2Jl4LQqamp8K/5Pw1S/AE63+3m1Z5/DbYF9MWeFkhmb+xgEn9Z9lvYxrFvn+Nep4qMVZIps9NXnuC7+Z90QtuiOKvQhr0BjYR8UqsUIGiMDzEFSX6YKhKgP39oRVc9W2M9jvLcJXD7WNmOphJo04JJf33FjyD8XmQwX3tNJgnxXH0re4uAbcrLBOdFsDwwwC7JzFYjLyTu2JpECzFTt5g=
  - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
  - secure: wMG1exLfaEYarKEVVG37sb2Mf9GGggNbuNdWfR4aA+4WpaD1NDBHmfM+xjoIj00HY9O8ZEOuObv4DM47XuTk6i6L3Y9N8lNJ11gKUGNkSZaagjxdpFtf+JpQMO7tBDG5Jg0/fjhL8yC9UXuTFZA9vF+HVdls07fTnxuOdMiCitaf4NhnHZenglH9I3nr1QWKYn4IwmDeg89GS7hUJ7Mn0qlCtuzm0fmcUHB/EmCSH97tSdrAdUUK96p8BSb8xWBhjrBuZzL5mec0jfj63IMgVnKvwx83PXL+Ex/2QeYyXjwR1aVWuM9Gx4q2iUX7IDgE9uKxsMyhd6WEClIHOuhYawfIeAZ+VAxZajrmp2qv6FreqPBvjsnWWf7a06/APFEbt2anoJKsXGaTqVFiSt/Ra0f0c5mvNk2zJK3TXIFqBr9wMn+QnPoG1XikADqT/2vGdHZIS04++P+bpgUcxPAPHBCuO0mFIYxsGpT1CHfN0v5fZ/U8j8mV0zmG1H8431ImP8PhjjEZP8binCSRT5IZ/8XHoAxAxX2pdvJiAWYFhGaxhfvtRHpG/38KKZ+29HwwZln10x69KaBFLvJdROF0PQsgO2UTlV8iKyoEeg+rAk36VIcsVaYMi0Odk1fswFwqA3uMVN+5Ain+wctssuIfkCktOwkZj+D2el3ZtOp4SPk=
  - secure: SU3WJz0qPZIK9HCXT4dVOWlP5PeuYwKASDei4x3qolPtEcqOAU923AafbC2fv+xfXr9shQZyyWmJVHbtO/XPa2B+Ck4NAsJGDFNArLFe+xF/BDiPrjmhXl7tveZ9oIsB4WY2NSGk6SwMM3TiF/5MmzX2LTDuSEum/AeLKvXRE9oDuflKN5Ok0an6JMMgH0SeSoNoB33N6q/5+bpfC0r67BAVjbKffKuJ4ZCq+0tDtqnhqxFt6lARcnc+5HvTD/sKK536klW8nUhDb3Nbogwo+HW5awv1tFhM1x0Tr0adqEk7bZBwCnLEE1o7lXiDyo56VnpGQjPQhc7xwumvO2JwBE6m9kCRTbcz77U+3GDUE0e5rGLdKdxEZjXqFFY6W0lUYa5WkCOKik+ApJRZQycDqKlhwdbL4pBynpCxdTauPXqZvCVdCZfqJjaB6Qb9h8Lz8gz3o6zSKDgWM3VXeC5MWaPwoZjjgaR4bYlPT6chfDWvEdze9/c/IUX6mtmwYOkZVo+iCGakNtUaVO9+O9sNsj3pl8sHIhKOR7J2sFJasCfpPrQwfNzM4Gf/cUHBHWb2Tz69KG+UyTxOgw7mnSzJlyWgNyrvFtevswhLG64GE0Y3KjHR4KhXzz5i4nT6K2A2fTRcC8PFf0b7VBIT9Xl25rFiZJ8H5wUi+kCRl20TLqk=
  - SENTRY_ORG=randytarampi
  - SENTRY_PROJECT=blog
before_install:
- uname -a
- lscpu
- npm install -g npm
- if [ -z "$TRAVIS_TAG" ]; then export NODE_ENV=prd; else export NODE_ENV=dev; fi;
script: npm test
after_success:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.photos.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- if [ -z "$TRAVIS_TAG" ]; then if [[ "$TRAVIS_COMMIT_MESSAGE" != *"[Travis] Prepare version"* ]]; then
  npm version minor; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
  fi; fi;
deploy:
  provider: releases
  api_key:
    secure: Z1c6P5FT2oy8HGsLLY3/KKg0uODqD3E98bFk42uh7CxiOCZjhLysh49ZSloeFkKPjHxRf604F//af9fFhjVO0X6kp80y821+8sUnxj6rYQrLTOeqYYzbHBHUfcb9lIBLTPDy1Bb0QU5Tl6aCtxkRa/p7cO+5w6RNHsQZ1UYTP+KqwIcSvHI1XIJWXgKLxOB+xCrZ5DwPQBGm5oeZc9If2fVuA9nyUr/cOGgoLBMArWkWZR8xsrbdNl6QjzZdNl55dyxLNMiiQ3kNpeiXAYd0ZnTWrqLPrBzGcor9crrg1Bxmc9FP17A1q0XwOmQ921ha+ICCEoTqauDiV0OOlmaXq6GxMg2S/qC+TSZTaL5E0WCol1Drrph8YUJYEc5Dcd0CdpGUsdPkAMueiZ6xacgALpeTVTvg9eeFk5O7DF6rs5zJwdaRu4YtjGFjYCf3rkHYQlmOWTdVssvpVBuXCgm6t1yQI0KRpxmY7qGfyoRKt4K1fNdyDIkrnnyK9oovxWBYWehatd4jL1VXt/bEHmG1GX39cbzBXhiCbxZQ6HaJM7u/DOylt4o1nsOSH6ehMgz09nb9k11GwZAYN3CPrUyS3hxoQeTa/HBpshxtjFejZ6Ug07909F6NjxnbBCM1QWFMI5VpHLChgWPzZFOYC3rI9PmIzQnGkRAxNbz34/+oHmQ=
  file: me.blog.tar.gz
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- if [ "$TRAVIS_TAG" ]; then npm version preminor -m "[Travis] Prepare version %s";
  git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:master; fi;
notifications:
  slack:
    secure: wcPjg9yq8eMkkec9AMsl7wnT4jvyZH9dHgdv5eWCo5F4L0T/3tsznI7C2kmsyeDpveLvDdovnqoU6Jvd+OThPPF74btI5MRz6yw3G3YMv77aTON1HGSN4QHjdIM2P16Ug5qYkZeL94QfXknNX4xUb+fBdb2vphMYPjVPIkwfBF9eV07EPR/MZbv29DKxzST6rx/CP5inZZPl9zEsPdcJQory+A5q3RkGRXGjCz4GhjweDy0ywoQQ85EKfiyOke6I6XhCY15ZPh0HYHIFy8lsJZfIVRsWNXY1twCKLX3v+iB3o8POFgICQV+HMCc4J+Q4BAVe02uZtghwOZvmL4+ShrZijNFMn0KXUxOXnM0p3n08icIasIpGNwZswOC5kJ/iUh0wjI12fGVLCVwOWpclaoIskJDSF0BLTyB0p48CUjYPO1+8nzIC1Llz072r2p8ZO79eAK7O0MoxknEkEKwfH65XcsSID0Kc7zjR7AE1InsNmnDFcrogJnUh1zOHXcRrk84TTKsdaNSl4/a5plGkmC3BQfUJHcawYpI1VRy2bKmCP6U4kxQNejvMKsuyW7rPHmE/msSwvDHgq2bX4O9Nloqg+3Q35rWA/lftlBZts8wTFM/YkRm3Xsssiee39dtUV7NU+u+RuWPx23Z/rYGB886X8O+QoktTjhoVRvNjIvs=
